CREATE DATABASE IF NOT EXISTS sirius CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE sirius;

CREATE TABLE users (
  uid VARCHAR(128) NOT NULL,
  pseudo VARCHAR(512) NOT NULL DEFAULT '',
  email VARCHAR(512) NULL DEFAULT NULL,
  password_hash VARCHAR(255) NULL DEFAULT NULL,
  wallet_gold INT NOT NULL DEFAULT 500,
  wallet_gems INT NOT NULL DEFAULT 50,
  difficulty_mode VARCHAR(32) NOT NULL DEFAULT 'normal',
  is_demo_mode TINYINT(1) NOT NULL DEFAULT 1,
  unlocked_breeds JSON NOT NULL,
  unlocked_skins JSON NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (uid),
  UNIQUE KEY uq_users_email (email)
) ENGINE=InnoDB;

CREATE TABLE inventory (
  owner_id VARCHAR(128) NOT NULL,
  croquettes INT NOT NULL DEFAULT 0,
  water_bottle INT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (owner_id),
  CONSTRAINT fk_inventory_owner FOREIGN KEY (owner_id) REFERENCES users (uid) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE dogs (
  id CHAR(36) NOT NULL,
  owner_id VARCHAR(128) NOT NULL,
  name VARCHAR(512) NOT NULL,
  breed VARCHAR(128) NOT NULL DEFAULT 'golden_retriever',
  food INT NOT NULL DEFAULT 100,
  water INT NOT NULL DEFAULT 100,
  health INT NOT NULL DEFAULT 100,
  is_sick TINYINT(1) NOT NULL DEFAULT 0,
  last_update_ms BIGINT NOT NULL,
  abandonment_pending_video TINYINT(1) NOT NULL DEFAULT 0,
  abandonment_marked_at DATETIME(3) NULL DEFAULT NULL,
  active_skin_id VARCHAR(128) NULL DEFAULT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_dogs_owner_id (owner_id),
  CONSTRAINT fk_dogs_owner FOREIGN KEY (owner_id) REFERENCES users (uid) ON DELETE CASCADE
) ENGINE=InnoDB;
